### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by srijs** [shinh/tel_ldr#1]
Hi, I stumbled across this project, fiddled a bit around and would like to publish my modifications. Unfortunately, you don't specify under which license this source code is released. Could you please choose a license which terms you like (you can go to http://choosealicense.com/ for guidance), and release your project under this license?

**Comment by shinh** [comment]
Done. Now this is under MIT license.

https://github.com/shinh/tel_ldr/commit/e5bf6b8e060f7932c904ea38d0aa6d61f014b543
